version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/


volumes:
  static_value:
  media_value:
