# Generated by Django 3.2 on 2023-09-19 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(through='goods.OrderItem', to='goods.Goods'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AddField(
            model_name='image',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.goods', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='goods',
            name='additive_type',
            field=models.ManyToManyField(blank=True, to='goods.HookahAdditive', verbose_name='Тип добавки для кальяна'),
        ),
        migrations.AddField(
            model_name='goods',
            name='hookah_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.hookahtype', verbose_name='Тип кальяна'),
        ),
        migrations.AddField(
            model_name='goods',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='goods_img', to='goods.Image'),
        ),
        migrations.AddField(
            model_name='goods',
            name='subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.goodssubtype', verbose_name='Тип товара'),
        ),
        migrations.AddField(
            model_name='goods',
            name='tobacco_type',
            field=models.ManyToManyField(blank=True, to='goods.HookahTobacco', verbose_name='Тип табака'),
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goods.goodstype', verbose_name='Тип меню'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_favorites', to='goods.goods'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('goods', 'user'), name='shopping_cart_unique'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('goods', 'user'), name='favorite_unique'),
        ),
    ]
