# Generated by Django 3.2 on 2023-09-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodssubtype_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodssubtype',
            name='image',
        ),
        migrations.AddField(
            model_name='goodssubtype',
            name='gif',
            field=models.ImageField(blank=True, upload_to='backend_media/', verbose_name='Гифка'),
        ),
        migrations.AddField(
            model_name='goodssubtype',
            name='icon',
            field=models.ImageField(blank=True, upload_to='backend_media/', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='hookahadditive',
            name='price',
            field=models.IntegerField(default=100, verbose_name='Цена добавки для кальяна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='additive_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена добавки для кальяна'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='additive_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена добавки для кальяна'),
        ),
    ]
