# Generated by Django 3.2 on 2023-09-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodssubtype',
            name='image',
            field=models.ImageField(blank=True, upload_to='backend_media/', verbose_name='Изображение'),
        ),
    ]
