# Generated by Django 3.2 on 2023-09-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20230927_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='additive_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tobacco_type',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='additive_type',
            field=models.CharField(default=100, max_length=50, verbose_name='Тип добавки для кальяна'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tobacco_type',
            field=models.CharField(default=100, max_length=50, verbose_name='Тип табака'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='additive_type',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Тип добавки для кальяна'),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='tobacco_type',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Тип табака'),
        ),
    ]
